sudo: false
language: generic

matrix:
  include:

    - env: CXX="g++-4.7"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-4.7

    - env: CXX="g++-4.7" CPP11="-DCPP11:int=1"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-4.7

    - env: CXX="g++-4.8"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-4.8

    - env: CXX="g++-4.8" CPP11="-DCPP11:int=1"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-4.8

    - env: CXX="g++-4.9"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-4.9

    - env: CXX="g++-4.9" CPP11="-DCPP11:int=1"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-4.9

    - env: CXX="g++-5"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-5

    - env: CXX="g++-5" CPP11="-DCPP11:int=1"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-5

    - env: CXX="g++-6"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-6

    - env: CXX="g++-6" CPP11="-DCPP11:int=1"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-6

    - env: CXX="g++-7"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-7

    - env: CXX="g++-7" CPP11="-DCPP11:int=1"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-7

    - env: CXX="g++-8"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-8

    - env: CXX="g++-8" CPP11="-DCPP11:int=1"
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: valgrind g++-8

    - env: CXX="clang++-3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages: valgrind clang++-3.6

    - env: CXX="clang++-3.6" CPP11="-DCPP11:int=1"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages: valgrind clang++-3.6

    - env: CXX="clang++-4.0"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages: valgrind clang++-4.0

    - env: CXX="clang++-4.0" CPP11="-DCPP11:int=1"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages: valgrind clang++-4.0

    - env: CXX="clang++-5.0"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages: valgrind clang++-5.0

    - env: CXX="clang++-5.0" CPP11="-DCPP11:int=1"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages: valgrind clang++-5.0

    - env: CXX="clang++-6.0"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages: valgrind clang++-6.0

    - env: CXX="clang++-6.0" CPP11="-DCPP11:int=1"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages: valgrind clang++-6.0


before_install:
  - wget https://github.com/google/googletest/archive/release-1.7.0.zip && unzip release-1.7.0.zip && (cd googletest-release-1.7.0 && cmake . && make)
  - export GTEST_ROOT=${TRAVIS_BUILD_DIR}/googletest-release-1.7.0


script:
  - ${CXX} --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. ${CPP11} && make VERBOSE=1 && ./minijson_reader_tests && valgrind --error-exitcode=42 --leak-check=full ./minijson_reader_tests
