sudo: false
language: generic

env:
  - CXX="g++-4.7"
  - CXX="g++-4.7" CPP11="-DCPP11:int=1"
  - CXX="g++-4.8"
  - CXX="g++-4.8" CPP11="-DCPP11:int=1"
  - CXX="g++-4.9"
  - CXX="g++-4.9" CPP11="-DCPP11:int=1"
  - CXX="g++-5"
  - CXX="g++-5" CPP11="-DCPP11:int=1"
  - CXX="g++-6"
  - CXX="g++-6" CPP11="-DCPP11:int=1"
  - CXX="g++-7"
  - CXX="g++-7" CPP11="-DCPP11:int=1"
  - CXX="g++-8"
  - CXX="g++-8" CPP11="-DCPP11:int=1"
  - CXX="clang++-3.6"
  - CXX="clang++-3.6" CPP11="-DCPP11:int=1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.7
      - g++-4.8
      - g++-4.9
      - g++-5
      - g++-6
      - g++-7
      - g++-8
      - clang-3.6

before_install:
  - wget https://github.com/google/googletest/archive/release-1.8.1.zip && unzip release-1.8.1.zip && (cd googletest-release-1.8.1 && cmake . && make)
  - export GTEST_ROOT=${TRAVIS_BUILD_DIR}/googletest-release-1.8.1

script:
  - ${CXX} --version
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. ${CPP11} && make VERBOSE=1 && ./minijson_reader_tests
